version: '3.9'
services: 
    backend:
        image: vladyslavstepanenko1/mean-stack-app-backend:latest
        depends_on: 
            - db
    frontend:
        image: vladyslavstepanenko1/mean-stack-app-frontend:latest
    db:
        image: mongo:latest
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - '49001:80'