version: '3.9'
services: 
    backend:
        build:
            context: .
            dockerfile: ./backend/docker/Dockerfile
        depends_on: 
            - db
    frontend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
    db:
        image: mongo:latest
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - '49001:80'