version: '3.9'
services: 
    backend:
        image: vladyslavstepanenko1/mean-stack-app-backend:latest
        depends_on: 
            - db
    frontend:
        image: vladyslavstepanenko1/mean-stack-app-frontend:latest
        ports: 
            - '49002:80'
    db:
        image: mongo:latest