pipeline{
    agent any
    environment{
        BACKEND_IMAGE_NAME = 'vladyslavstepanenko1/mean-stack-app-backend'
        FRONTEND_IMAGE_NAME = 'vladyslavstepanenko1/mean-stack-app-frontend'
    }
    stages{
        stage('Build backend'){
            steps{
                // Build docker image for backend
                sh "docker build -t ${BACKEND_IMAGE_NAME} -f ./backend/docker/Dockerfile ."
            }
        }
        stage('Build frontend'){
            steps{
                //Build docker image for frontend
                sh "docker build -t ${FRONTEND_IMAGE_NAME} -f ./docker/Dockerfile ."
            }
        }
        stage('Push images'){
            steps{
                // push images to dockerhub registry
                sh "docker push ${BACKEND_IMAGE_NAME}:latest"
                sh "docker push ${FRONTEND_IMAGE_NAME}:latest"
            }
        }
        stage('Deploy'){
            steps{
                // pull images from registry
                // run containers with docker-compose
                sh 'echo deploying...'
            }
        }
    }
}