pipeline{
    agent any
    environment{
        BACKEND_IMAGE_NAME = 'vladyslavstepanenko1/mean-stack-app-backend'
        FRONTEND_IMAGE_NAME = 'vladyslavstepanenko1/mean-stack-app-frontend'
    }
    stages{
        stage('Build backend'){
            steps{
                // Build docker image for backend
                sh 'docker build -t ${BACKEND_IMAGE_NAME} -f ./backend/docker/Dockerfile .'
            }
        }
        stage('Build frontend'){
            steps{
                //Build docker image for frontend
                sh 'docker build -t ${FRONTEND_IMAGE_NAME} -f ./docker/Dockerfile .'
            }
        }
        stage('Push images'){
            steps{
                withCredentials([usernamePassword(credentialsId:'dockerHubCredentials', 
                                                  usernameVariable:'DOCKER_USER',
                                                  passwordVariable:'DOCKER_PASSWORD')]){
                    // login to docker hub
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASSWORD'
                    // push images to docker hub registry
                    sh 'docker push $BACKEND_IMAGE_NAME:latest'
                    sh 'docker push $FRONTEND_IMAGE_NAME:latest'
                }
            }
        }
        stage('Deploy'){
            steps{
                // pull images from registry
                withCredentials([usernamePassword(credentialsId:'dockerHubCredentials', 
                                                  usernameVariable:'DOCKER_USER',
                                                  passwordVariable:'DOCKER_PASSWORD')]){
                    sh 'docker login -u $DOCKER_USER -p $DOCKER_PASSWORD'
                }
                // run containers with docker-compose
                sh 'docker-compose up -d'
            }
        }
    }
}